-- =====================================================================
--  Dessineo Ary ! — catégories et mots
--  À exécuter après schema.sql. Ré-exécutable : les doublons sont ignorés.
--  Pour ajouter des mots, complétez simplement la liste et ré-exécutez.
--  alternatives = autres réponses acceptées (synonymes).
-- =====================================================================

insert into public.categories (name, emoji, sort_order) values
  ('Musique', '🎵', 1),
  ('Objets du quotidien', '🏠', 2),
  ('Plats & cuisine', '🍽️', 3),
  ('Animaux', '🐾', 4),
  ('Sports & loisirs', '⚽', 5),
  ('Métiers', '💼', 6),
  ('Transports', '🚗', 7),
  ('Nature & lieux', '🌋', 8),
  ('Madagascar', '🦎', 9)
on conflict (name) do update set emoji = excluded.emoji, sort_order = excluded.sort_order;

insert into public.words (category_id, word, alternatives)
select c.id, v.word, v.alternatives
from (values
  -- Musique
  ('Musique', 'Guitare', '{}'::text[]),
  ('Musique', 'Guitare électrique', '{}'),
  ('Musique', 'Piano', '{}'),
  ('Musique', 'Batterie', '{}'),
  ('Musique', 'Violon', '{}'),
  ('Musique', 'Trompette', '{}'),
  ('Musique', 'Micro', '{microphone}'),
  ('Musique', 'Casque audio', '{casque}'),
  ('Musique', 'Saxophone', '{saxo}'),
  ('Musique', 'Accordéon', '{}'),
  ('Musique', 'Harpe', '{}'),
  ('Musique', 'Flûte', '{}'),
  ('Musique', 'Tambour', '{}'),
  ('Musique', 'Note de musique', '{note}'),
  ('Musique', 'Chef d''orchestre', '{}'),
  ('Musique', 'Concert', '{}'),
  ('Musique', 'Disque vinyle', '{vinyle,disque}'),
  ('Musique', 'Haut-parleur', '{enceinte}'),
  ('Musique', 'Karaoké', '{}'),
  ('Musique', 'Xylophone', '{}'),
  ('Musique', 'Partition', '{}'),
  ('Musique', 'Maracas', '{}'),
  ('Musique', 'Radio', '{}'),
  ('Musique', 'Platine DJ', '{dj,platine}'),
  ('Musique', 'Chorale', '{}'),
  ('Musique', 'Harmonica', '{}'),

  -- Objets du quotidien
  ('Objets du quotidien', 'Parapluie', '{}'),
  ('Objets du quotidien', 'Brosse à dents', '{}'),
  ('Objets du quotidien', 'Lunettes', '{}'),
  ('Objets du quotidien', 'Clé', '{clef}'),
  ('Objets du quotidien', 'Ciseaux', '{}'),
  ('Objets du quotidien', 'Chaise', '{}'),
  ('Objets du quotidien', 'Lampe', '{}'),
  ('Objets du quotidien', 'Téléphone', '{portable,smartphone}'),
  ('Objets du quotidien', 'Réveil', '{}'),
  ('Objets du quotidien', 'Miroir', '{}'),
  ('Objets du quotidien', 'Oreiller', '{coussin}'),
  ('Objets du quotidien', 'Fourchette', '{}'),
  ('Objets du quotidien', 'Cuillère', '{cuiller}'),
  ('Objets du quotidien', 'Bougie', '{}'),
  ('Objets du quotidien', 'Montre', '{}'),
  ('Objets du quotidien', 'Sac à dos', '{cartable}'),
  ('Objets du quotidien', 'Ampoule', '{}'),
  ('Objets du quotidien', 'Peigne', '{}'),
  ('Objets du quotidien', 'Savon', '{}'),
  ('Objets du quotidien', 'Télécommande', '{}'),
  ('Objets du quotidien', 'Ordinateur', '{ordi,pc}'),
  ('Objets du quotidien', 'Télévision', '{télé,tv}'),
  ('Objets du quotidien', 'Balai', '{}'),
  ('Objets du quotidien', 'Seau', '{}'),
  ('Objets du quotidien', 'Casserole', '{}'),
  ('Objets du quotidien', 'Bouteille', '{}'),
  ('Objets du quotidien', 'Porte-monnaie', '{portefeuille}'),
  ('Objets du quotidien', 'Cadenas', '{}'),
  ('Objets du quotidien', 'Ventilateur', '{}'),
  ('Objets du quotidien', 'Fer à repasser', '{}'),

  -- Plats & cuisine
  ('Plats & cuisine', 'Pizza', '{}'),
  ('Plats & cuisine', 'Hamburger', '{burger}'),
  ('Plats & cuisine', 'Frites', '{}'),
  ('Plats & cuisine', 'Spaghetti', '{pâtes,spaghettis}'),
  ('Plats & cuisine', 'Sushi', '{}'),
  ('Plats & cuisine', 'Croissant', '{}'),
  ('Plats & cuisine', 'Gâteau d''anniversaire', '{gâteau}'),
  ('Plats & cuisine', 'Glace', '{crème glacée}'),
  ('Plats & cuisine', 'Omelette', '{}'),
  ('Plats & cuisine', 'Sandwich', '{}'),
  ('Plats & cuisine', 'Soupe', '{}'),
  ('Plats & cuisine', 'Salade', '{}'),
  ('Plats & cuisine', 'Crêpe', '{}'),
  ('Plats & cuisine', 'Hot-dog', '{}'),
  ('Plats & cuisine', 'Brochette', '{}'),
  ('Plats & cuisine', 'Poulet rôti', '{poulet}'),
  ('Plats & cuisine', 'Riz', '{}'),
  ('Plats & cuisine', 'Banane', '{}'),
  ('Plats & cuisine', 'Pastèque', '{}'),
  ('Plats & cuisine', 'Ananas', '{}'),
  ('Plats & cuisine', 'Fromage', '{}'),
  ('Plats & cuisine', 'Baguette', '{pain}'),
  ('Plats & cuisine', 'Œuf au plat', '{oeuf}'),
  ('Plats & cuisine', 'Popcorn', '{pop-corn}'),
  ('Plats & cuisine', 'Donut', '{beignet}'),
  ('Plats & cuisine', 'Tacos', '{}'),
  ('Plats & cuisine', 'Chocolat', '{}'),
  ('Plats & cuisine', 'Café', '{}'),
  ('Plats & cuisine', 'Mangue', '{}'),
  ('Plats & cuisine', 'Brocoli', '{}'),

  -- Animaux
  ('Animaux', 'Chat', '{}'),
  ('Animaux', 'Chien', '{}'),
  ('Animaux', 'Éléphant', '{}'),
  ('Animaux', 'Girafe', '{}'),
  ('Animaux', 'Lion', '{}'),
  ('Animaux', 'Serpent', '{}'),
  ('Animaux', 'Tortue', '{}'),
  ('Animaux', 'Poisson', '{}'),
  ('Animaux', 'Requin', '{}'),
  ('Animaux', 'Pingouin', '{manchot}'),
  ('Animaux', 'Papillon', '{}'),
  ('Animaux', 'Araignée', '{}'),
  ('Animaux', 'Escargot', '{}'),
  ('Animaux', 'Crocodile', '{}'),
  ('Animaux', 'Singe', '{}'),
  ('Animaux', 'Lapin', '{}'),
  ('Animaux', 'Cheval', '{}'),
  ('Animaux', 'Vache', '{}'),
  ('Animaux', 'Poule', '{}'),
  ('Animaux', 'Canard', '{}'),
  ('Animaux', 'Hibou', '{chouette}'),
  ('Animaux', 'Abeille', '{}'),
  ('Animaux', 'Dauphin', '{}'),
  ('Animaux', 'Kangourou', '{}'),
  ('Animaux', 'Zèbre', '{}'),
  ('Animaux', 'Grenouille', '{}'),
  ('Animaux', 'Souris', '{}'),
  ('Animaux', 'Pieuvre', '{poulpe}'),
  ('Animaux', 'Coccinelle', '{}'),
  ('Animaux', 'Chameau', '{dromadaire}'),

  -- Sports & loisirs
  ('Sports & loisirs', 'Football', '{foot}'),
  ('Sports & loisirs', 'Basket', '{basketball,basket-ball}'),
  ('Sports & loisirs', 'Tennis', '{}'),
  ('Sports & loisirs', 'Natation', '{nager}'),
  ('Sports & loisirs', 'Vélo', '{bicyclette,cyclisme}'),
  ('Sports & loisirs', 'Ski', '{}'),
  ('Sports & loisirs', 'Boxe', '{}'),
  ('Sports & loisirs', 'Pétanque', '{boules}'),
  ('Sports & loisirs', 'Surf', '{}'),
  ('Sports & loisirs', 'Pêche', '{}'),
  ('Sports & loisirs', 'Course à pied', '{course,jogging,running}'),
  ('Sports & loisirs', 'Volley', '{volleyball,volley-ball}'),
  ('Sports & loisirs', 'Rugby', '{}'),
  ('Sports & loisirs', 'Judo', '{}'),
  ('Sports & loisirs', 'Skateboard', '{skate}'),
  ('Sports & loisirs', 'Golf', '{}'),
  ('Sports & loisirs', 'Ping-pong', '{tennis de table}'),
  ('Sports & loisirs', 'Escalade', '{}'),
  ('Sports & loisirs', 'Danse', '{}'),
  ('Sports & loisirs', 'Échecs', '{}'),
  ('Sports & loisirs', 'Cerf-volant', '{}'),
  ('Sports & loisirs', 'Camping', '{}'),
  ('Sports & loisirs', 'Bowling', '{}'),
  ('Sports & loisirs', 'Plongée', '{}'),
  ('Sports & loisirs', 'Corde à sauter', '{saut à la corde}'),
  ('Sports & loisirs', 'Yoga', '{}'),
  ('Sports & loisirs', 'Équitation', '{}'),
  ('Sports & loisirs', 'Karaté', '{}'),
  ('Sports & loisirs', 'Trampoline', '{}'),
  ('Sports & loisirs', 'Jeux vidéo', '{jeu vidéo,manette}'),

  -- Métiers
  ('Métiers', 'Médecin', '{docteur}'),
  ('Métiers', 'Pompier', '{}'),
  ('Métiers', 'Policier', '{police,gendarme}'),
  ('Métiers', 'Boulanger', '{}'),
  ('Métiers', 'Cuisinier', '{chef,chef cuisinier}'),
  ('Métiers', 'Professeur', '{prof,enseignant,maître}'),
  ('Métiers', 'Pilote', '{}'),
  ('Métiers', 'Astronaute', '{cosmonaute}'),
  ('Métiers', 'Coiffeur', '{coiffeuse}'),
  ('Métiers', 'Facteur', '{}'),
  ('Métiers', 'Mécanicien', '{garagiste}'),
  ('Métiers', 'Agriculteur', '{fermier,paysan,cultivateur}'),
  ('Métiers', 'Pêcheur', '{}'),
  ('Métiers', 'Peintre', '{}'),
  ('Métiers', 'Photographe', '{}'),
  ('Métiers', 'Dentiste', '{}'),
  ('Métiers', 'Infirmier', '{infirmière}'),
  ('Métiers', 'Chanteur', '{chanteuse}'),
  ('Métiers', 'Clown', '{}'),
  ('Métiers', 'Magicien', '{}'),
  ('Métiers', 'Plombier', '{}'),
  ('Métiers', 'Électricien', '{}'),
  ('Métiers', 'Jardinier', '{}'),
  ('Métiers', 'Juge', '{}'),
  ('Métiers', 'Serveur', '{serveuse}'),
  ('Métiers', 'Chauffeur de taxi', '{chauffeur,taximan}'),
  ('Métiers', 'Maçon', '{}'),
  ('Métiers', 'Vétérinaire', '{véto}'),
  ('Métiers', 'Architecte', '{}'),
  ('Métiers', 'Couturier', '{couturière,tailleur}'),

  -- Transports
  ('Transports', 'Voiture', '{auto}'),
  ('Transports', 'Bus', '{autobus}'),
  ('Transports', 'Avion', '{}'),
  ('Transports', 'Bateau', '{navire}'),
  ('Transports', 'Train', '{}'),
  ('Transports', 'Moto', '{motocyclette}'),
  ('Transports', 'Hélicoptère', '{}'),
  ('Transports', 'Fusée', '{}'),
  ('Transports', 'Camion', '{}'),
  ('Transports', 'Trottinette', '{}'),
  ('Transports', 'Tracteur', '{}'),
  ('Transports', 'Sous-marin', '{}'),
  ('Transports', 'Montgolfière', '{}'),
  ('Transports', 'Ambulance', '{}'),
  ('Transports', 'Taxi', '{}'),
  ('Transports', 'Métro', '{}'),
  ('Transports', 'Voilier', '{}'),
  ('Transports', 'Parachute', '{}'),
  ('Transports', 'Camion de pompiers', '{}'),
  ('Transports', 'Tramway', '{tram}'),
  ('Transports', 'Jet-ski', '{}'),
  ('Transports', 'Scooter', '{}'),
  ('Transports', 'Téléphérique', '{}'),
  ('Transports', 'Paquebot', '{}'),
  ('Transports', 'Soucoupe volante', '{ovni}'),

  -- Nature & lieux
  ('Nature & lieux', 'Soleil', '{}'),
  ('Nature & lieux', 'Lune', '{}'),
  ('Nature & lieux', 'Étoile', '{}'),
  ('Nature & lieux', 'Nuage', '{}'),
  ('Nature & lieux', 'Arc-en-ciel', '{}'),
  ('Nature & lieux', 'Montagne', '{}'),
  ('Nature & lieux', 'Volcan', '{}'),
  ('Nature & lieux', 'Plage', '{}'),
  ('Nature & lieux', 'Île', '{}'),
  ('Nature & lieux', 'Cascade', '{chute d''eau}'),
  ('Nature & lieux', 'Forêt', '{}'),
  ('Nature & lieux', 'Désert', '{}'),
  ('Nature & lieux', 'Arbre', '{}'),
  ('Nature & lieux', 'Fleur', '{}'),
  ('Nature & lieux', 'Cactus', '{}'),
  ('Nature & lieux', 'Rivière', '{fleuve}'),
  ('Nature & lieux', 'Pluie', '{}'),
  ('Nature & lieux', 'Bonhomme de neige', '{}'),
  ('Nature & lieux', 'Éclair', '{foudre,orage}'),
  ('Nature & lieux', 'Tornade', '{tempête,cyclone}'),
  ('Nature & lieux', 'Grotte', '{caverne}'),
  ('Nature & lieux', 'Château', '{}'),
  ('Nature & lieux', 'Phare', '{}'),
  ('Nature & lieux', 'Pont', '{}'),
  ('Nature & lieux', 'Pyramide', '{}'),
  ('Nature & lieux', 'Igloo', '{}'),
  ('Nature & lieux', 'Tour Eiffel', '{}'),
  ('Nature & lieux', 'Hôpital', '{}'),
  ('Nature & lieux', 'École', '{}'),
  ('Nature & lieux', 'Marché', '{}'),

  -- Madagascar
  ('Madagascar', 'Baobab', '{}'),
  ('Madagascar', 'Zébu', '{}'),
  ('Madagascar', 'Lémurien', '{maki}'),
  ('Madagascar', 'Caméléon', '{}'),
  ('Madagascar', 'Rizière', '{}'),
  ('Madagascar', 'Pirogue', '{}'),
  ('Madagascar', 'Taxi-brousse', '{}'),
  ('Madagascar', 'Pousse-pousse', '{}'),
  ('Madagascar', 'Vanille', '{}'),
  ('Madagascar', 'Valiha', '{}'),
  ('Madagascar', 'Lamba', '{}'),
  ('Madagascar', 'Mofo gasy', '{mofo}'),
  ('Madagascar', 'Litchi', '{letchi}'),
  ('Madagascar', 'Tsingy', '{}'),
  ('Madagascar', 'Ravinala', '{arbre du voyageur}'),
  ('Madagascar', 'Fossa', '{}'),
  ('Madagascar', 'Charrette à zébus', '{charrette}'),
  ('Madagascar', 'Hira gasy', '{}'),
  ('Madagascar', 'Ariary', '{billet}'),
  ('Madagascar', 'Sobika', '{panier}'),
  ('Madagascar', 'Romazava', '{}'),
  ('Madagascar', 'Tortue radiée', '{}'),
  ('Madagascar', 'Mangrove', '{}'),
  ('Madagascar', 'Lac Anosy', '{}'),
  ('Madagascar', 'Allée des Baobabs', '{}')
) as v(category, word, alternatives)
join public.categories c on c.name = v.category
on conflict (category_id, word) do update set alternatives = excluded.alternatives;
